# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - energy-controller-front

on:
  push:
    branches: [ master ] # confirme se é 'master' mesmo
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: Portifolio_front/energy-controller

    steps:
      - uses: actions/checkout@v4

      - name: Debug repo tree (opcional)
        run: |
          pwd
          ls -la
          echo "---- procurando package.json ----"
          find . -maxdepth 3 -name package.json -print

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 22 também ok; evite 24 se seu app/ferramentas não suportarem
          cache: 'npm'
          cache-dependency-path: Portifolio_front/energy-controller/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Sobe só os artefatos prontos (dist) para o job de deploy
      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: Portifolio_front/energy-controller/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC64FB9D7711410CBA8D1549D1DEA049 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BBE7ED0090F04F889EC2F702D47A8FC4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4843D5FAFE44D6F9EA8186AF3F29B22 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'energy-controller-front'
          slot-name: 'Production'
          package: dist
